version: "3"

services:
  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
    env_file:
      - .dev.env
    links:
      - py2-db
      - py2-solr
      - py2-redis
      #- datapusher
    ports:
      - "0.0.0.0:5000:5000"
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions
    networks:
      - frontend
      - backend
    depends_on:
      - py2-db

  #datapusher:
  #  container_name: datapusher
  #  build:
  #    context: datapusher/
  #  ports:
  #    - "8800:8800"
  #  networks:
  #    - frontend
  #    - backend

  py2-db:
    container_name: py2-db
    env_file:
      - .dev.env
    environment:
      - PGDATA=/var/lib/postgresql/data/db
    build:
      context: postgresql/
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  #solr:
  #  container_name: solr
  #  build:
  #    context: solr/

  py2-solr:
    container_name: py2-solr
    image: solr:8.11.1
    networks:
      - backend
    env_file:
      - ./.dev.env
    environment:
      - CKAN_VERSION=2.9.5
      - CKAN_CORE_NAME=ckan
    volumes:
      - solr_data:/var/solr
      - ${PWD}/solr8/ckan_init_solr.sh:/docker-entrypoint-initdb.d/ckan_init_solr.sh

  py2-redis:
    container_name: py2-redis
    image: redis:alpine
    networks:
      - backend

volumes:
  ckan_storage:
  pg_data:
  solr_data:

networks:
  frontend:
  backend:
